### ISSUE TITLE
Uses vulnerable version of "got"

### ISSUE THREAD

**Issue by neil-hardlight** [vitalets/google-translate-api#100]
Running "npm audit" results in:

```
# npm audit report

got  <11.8.5
Severity: moderate
Got allows a redirect to a UNIX socket - https://github.com/advisories/GHSA-pfrx-2q88-qq97
No fix available
node_modules/@vitalets/google-translate-api/node_modules/got
  @vitalets/google-translate-api  *
  Depends on vulnerable versions of got
  node_modules/@vitalets/google-translate-api

2 moderate severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
```

**Comment by AidanWelch** [comment]
As far as I can tell this fork is only able to be slightly maintained, so I have [created a fork](https://github.com/AidanWelch/google-translate-api) that will continually be updated, and solves this issue by dropping `got` entirely.

**Comment by neil-hardlight** [comment]
Thanks Aidan - I've switched over to your fork.

**Comment by vitalets** [comment]
In new beta release v9 `got` [was replaced](https://github.com/vitalets/google-translate-api/issues/70#issuecomment-1282886088) with the latest `node-fetch`.
