### ISSUE TITLE
Support browser extensions

### ISSUE THREAD

**Issue by lmk123** [vitalets/google-translate-api#106]
The documentation says that this project cannot be used in browsers because of CORS, but in fact [browser extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) allow cross-domains.

I hope this project can support use in browser extensions, theoretically just by replacing got with [axios](https://github.com/axios/axios).

**Comment by vitalets** [comment]
In the latest [beta release](https://github.com/vitalets/google-translate-api/issues/70#issuecomment-1282886088) I've replaced got with node-fetch, that actually should work in browser context.
I would appreciate if you try it and share the result!

**Comment by lmk123** [comment]
Thanks for your work!

node-fetch seems to be supported only in Node.js. Its homepage says this:

> See Jason Miller's [isomorphic-unfetch](https://www.npmjs.com/package/isomorphic-unfetch) or Leonardo Quixada's [cross-fetch](https://github.com/lquixada/cross-fetch) for isomorphic usage (exports node-fetch for server-side, whatwg-fetch for client-side).

But isomorphic-unfetch has not been updated for two years, and cross-fetch is still using the v2.x version of node-fetch.

Probably axios is still the better solution.

**Comment by vitalets** [comment]
I've used node-fetch v2 that has `browser` field in package.json and bundler (webpack) should correctly use built-in fetch.
Also found interesting discussion in node-fetch repo https://github.com/node-fetch/node-fetch/issues/786

**Comment by vitalets** [comment]
Just checked new v9 - it works in browser extensions.
[Added documentation to readme](https://github.com/vitalets/google-translate-api/tree/v9#browser-extensions)
