### ISSUE TITLE
How to use this API with Python?

### ISSUE THREAD

**Issue by Peter-developer01** [vitalets/google-translate-api#111]

**Comment by vitalets** [comment]
This package is for Node.js. 
To use it with Python you can check out [this file](https://github.com/vitalets/google-translate-api/blob/b7bf3687e60c2e244e100a6c3b431ffa0865be77/src/index.ts#L36) and write own script using Python module for HTTP requests.

**Comment by Peter-developer01** [comment]
Thanks. I will try my best.
