### ISSUE TITLE
How does it work without a token?

### ISSUE THREAD

**Issue by barryvanderwiel** [vitalets/google-translate-api#114]
@vitalets the previous version and the original fork uses some "strange math" to generate a token and passes it with the request. Reading the current source code, it doesn't look like you are generating or passing a token. Would you mind elaborating how does it work?

**Comment by vitalets** [comment]
Since v9 library uses `translate.google.com/translate_a/single` url that returns translation without any tokens:
```
curl -X POST 'https://translate.google.com/translate_a/single?client=at&dt=t&dt=rm&dj=1' \
  -H 'Content-Type: application/x-www-form-urlencoded;charset=utf-8' \
  -d 'sl=en&tl=fr&q=hello'
```
Response:
```json
{
  "sentences": [
    {
      "trans": "Bonjour",
      "orig": "hello",
      "backend": 10
    },
    {
      "src_translit": "həˈlō"
    }
  ],
  "src": "en",
  "confidence": 1.0,
  "spell": {},
  "ld_result": {
    "srclangs": [
      "en"
    ],
    "srclangs_confidences": [
      1.0
    ],
    "extended_srclangs": [
      "en"
    ]
  }
}
```

**Comment by barryvanderwiel** [comment]
Thanks for sharing @vitalets 👍 Didn't know that.

Closing the issue.
