### ISSUE TITLE
TooManyRequestsError after first call

### ISSUE THREAD

**Issue by anhnv-nhsv** [vitalets/google-translate-api#116]
After the first time I call API, then everytime it got an error:

> 
> \node_modules\@vitalets\google-translate-api\dist\cjs\index.js:74
>             return (0, http_errors_1.default)(res.status, message);
>                                              ^
> 
> TooManyRequestsError: Too Many Requests IP: X.X.X.X, Time: 2023-05-31T09:05:50Z, Url: https://translate.google.com/translate_a/single?client=at&dt=t&dt=rm&dj=1
>     at Translator.buildError (XXX\node_modules\@vitalets\google-translate-api\dist\cjs\index.js:74:46)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Translator.translate (XXX\node_modules\@vitalets\google-translate-api\dist\cjs\index.js:29:19)
>     at async file:///XXX/report-v2.js:57:24
> 
> Node.js v18.15.0
> 

How can I fix this? Thanks.

**Comment by vitalets** [comment]
Could you try with proxy?

**Comment by anhnv-nhsv** [comment]
Thanks Vitalets. I've tried other proxy and it worked.
