### ISSUE TITLE
Unhandled Promise Rejection: Error.captureStackTrace is not a function

### ISSUE THREAD

**Issue by Kefir101** [vitalets/google-translate-api#118]
Running for react-native and expo app on windows, all I'm doing is a simple call using the documentation (in an async function). React native 69.9, expo sdk 46, react 18. Not sure what else to put.
![image](https://github.com/vitalets/google-translate-api/assets/82855176/43b59716-3e2b-44fb-8983-413903609140)

**Comment by vitalets** [comment]
Are you sure it's related to google-translate-api? I've check - library code [does not contain `captureStackTrace `](https://github.com/search?q=repo%3Avitalets%2Fgoogle-translate-api%20captureStackTrace&type=code)

**Comment by Kefir101** [comment]
Well, I changed those two lines of code to another api (https://www.npmjs.com/package/translate-google-api) and it worked just fine. So I'm guessing the error is with your google-translate-api.

**Comment by Kefir101** [comment]
I have come back to this specific API because the one I found that works doesn't have the feature that I now need to output the detected language. So I am reopening this issue.
