### ISSUE TITLE
Response translation returns wrong language

### ISSUE THREAD

**Issue by jorismertz** [vitalets/google-translate-api#120]
Hi, i use this library to translate my website in batches and have noticed that after it's done with translating to polish every language that comes after that also gets translated to polish. I have checked that the language code being passed in is correct. When changing the order of languages or excluding polish the same happens but with a different language. 

Is this a caching issue or what could cause this? i'm totally at a loss right now, thanks in advance.

**Comment by jorismertz** [comment]
This turned out to be a very obscure bug with dynamic imports. Not the fault of this library, thanks for the amazing work!

**Comment by vitalets** [comment]
You are welcome :)
