### ISSUE TITLE
Google Translate API limit of v1

### ISSUE THREAD

**Issue by kkm** [vitalets/google-translate-api#122]
I've been on the hunt for information regarding the Google Translate limit for quite some time now, and I'm pretty certain it pertains to version 1. Could anyone assist me in locating a website or resource that sheds light on this limit?

And I've also come across some interesting links discussing v1, but I haven't stumbled upon a precise website. Here's one I found: https://developers.googleblog.com/2011/08/paid-version-of-google-translate-api.html

**Comment by vitalets** [comment]
This package does not use paid version of Google translate API. I think it's better to contact their support.
For v2 and v3 these is quotas info in documentation, maybe it helps: https://cloud.google.com/translate/quotas
