### ISSUE TITLE
Access 404 to https://translate.google.com

### ISSUE THREAD

**Issue by Missper** [vitalets/google-translate-api#129]
[vite-plugin-auto-i18n] FetchError: request to https://translate.google.com/translate_a/single?client=at&dt=t&dt=rm&dj=1 failed, reason: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:7890
error during build:
Error: FetchError: request to https://translate.google.com/translate_a/single?client=at&dt=t&dt=rm&dj=1 failed, reason: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:789

**Comment by vitalets** [comment]
Could you provide full code snippet?
It's expected, that GET request to the translate url returns 404.
Or please try code from [example](https://github.com/vitalets/google-translate-api/blob/master/examples/simple.ts).

**Comment by Missper** [comment]
抱歉抱歉, 我刚刚找出了问题所在, 真正的问题不是来源于你的项目.
我正在使用一个叫做vite-plugin-auto-i18n的vue插件, 他竟然内置了一个代理地址为127.0.0.1:7890, 这直接导致了我本地请求变为404
