### ISSUE TITLE
已经执行了npm install --save child_process fs，还是一直提示我找不到

### ISSUE THREAD

**Issue by SundarZhou** [vitalets/google-translate-api#23]
![image](https://user-images.githubusercontent.com/17945090/55790567-3981c400-5aef-11e9-98d8-70d62e83fd7e.png)
我已经安提示执行过npm install --save child_process fs，运行npm run dev 后还是一直报一样的错误

**Comment by vitalets** [comment]
Please, try to translate in English.
Feel free to reopen.
