### ISSUE TITLE
Question: Any way to disable spelling correction and or language correction?

### ISSUE THREAD

**Issue by zenflow** [vitalets/google-translate-api#27]

**Comment by vitalets** [comment]
Could you show an example how is now and what you expect?

**Comment by zenflow** [comment]
@vitalets thanks for your quick response (and sorry for my delay)

---

Taking spelling correction for example:

### How it is now:

From the documentation:

```js
translate('I spea Dutch!', {from: 'en', to: 'nl'}).then(res => {
    console.log(res.text); //=> Ik spreek Nederlands!
    console.log(res.from.text.autoCorrected);  //=> true
    console.log(res.from.text.value); //=> I [speak] Dutch!
})
```

### What I would like:

An option to disable the "auto correction" of the text to be translated:

```js
translate('I spea Dutch!', {from: 'en', to: 'nl', autoCorrect: false}).then(res => {
    console.log(res.text); //=> Ik spea Nederlands!
    console.log(res.from.text.autoCorrected);  //=> false
    console.log(res.from.text.value); //=> I spea Dutch!
})
```

---

Is this possible with the API that Google Translate provides?

If so, I would love to contribute a PR adding the option!

p.s. Thanks so much for maintaining this awesome module <3

**Comment by vitalets** [comment]
@zenflow So you want to ignore incorrect words?
I doubt that such option exists in Google API. Because the translation of whole phrase highly depends on every word. If you need to translate word by word I think it's better to split string on words and translate them separately.

**Comment by coltongit** [comment]
This. It's a limitation of the API itself and, in most cases, isn't really necessary in most applications.
