### ISSUE TITLE
translate result is a text file, not a json string

### ISSUE THREAD

**Issue by Gontte** [vitalets/google-translate-api#29]
i got an error: SyntaxError: Unexpected token  in JSON at position 0
Then I copied the link to the browser and got a downloaded txt file.

**Comment by vitalets** [comment]
Could you show a link that you have used?

**Comment by Gontte** [comment]
open this [link](https://translate.google.cn/translate_a/single?client=gtx&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=sky&tk=192176.192176) and you will get to a txt file

**Comment by vitalets** [comment]
This is actually json file, that can be parsed in code.
```json
[[["sky","sky",null,null,0],[null,null,null,"skī"]],null, 
```
How do you use google-translate-api for this file?

**Comment by Gontte** [comment]
Below is my code：
```js
const translate = require('@vitalets/google-translate-api');
translate('sky', { to: 'en', tld: 'cn', client: 'gtx' })
  .then(res => console.log(res))
  .catch(err => console.log(err))
```
The result should be returned by json. I don't know why it is a txt file.

**Comment by vitalets** [comment]
I'm getting result as json, e.g. I can print `.text` field:
```js
const translate = require('@vitalets/google-translate-api');
translate('sky', { to: 'en', tld: 'cn', client: 'gtx' })
  .then(res => console.log(res.text)) // outputs "sky"
  .catch(err => console.log(err))
```

**Comment by Gontte** [comment]
Thank you！
I found the reason, because I use it in the webpage, so I get a text file and the following error.
![image](https://user-images.githubusercontent.com/10473665/60798409-ae72a180-a1a3-11e9-9d04-90b58f1a186d.png)

**Comment by vitalets** [comment]
Yes. Unfortunately `https://translate.google.cn` does not provide CORS headers allowing to send requests from web context.
