### ISSUE TITLE
Response code 503 (Service Unavailable)

### ISSUE THREAD

**Issue by nvtuan305** [vitalets/google-translate-api#3]
I got issue above when call from inside Google VM instance. It will work again after 1-2 days.

> Response code 503 (Service Unavailable)\nUrl: https://translate.google.com/translate_a/single?client=t&sl=en&tl=vi&hl=vi&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=32434&tk=560583.924797","stack":"HTTPError: Response code 503 (Service Unavailable)\n at stream.catch.then.data (/source/node_modules/got/index.js:123:13)\n at tryCatcher (/source/node_modules/bluebird/js/release/util.js:16:23)\n at Promise._settlePromiseFromHandler (/source/node_modules/bluebird/js/release/promise.js:512:31)\n at Promise._settlePromise (/source/node_modules/bluebird/js/release/promise.js:569:18)\n at Promise._settlePromise0 (/source/node_modules/bluebird/js/release/promise.js:614:10)\n at Promise._settlePromises (/source/node_modules/bluebird/js/release/promise.js:694:18)\n at _drainQueueStep (/source/node_modules/bluebird/js/release/async.js:138:12)\n at _drainQueue (/source/node_modules/bluebird/js/release/async.js:131:9)\n at Async._drainQueues (/source/node_modules/bluebird/js/release/async.js:147:5)\n at Immediate.Async.drainQueues (/source/node_modules/bluebird/js/release/async.js:17:14)\n at Immediate.args.(anonymous function) [as _onImmediate] (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)\n at runCallback (timers.js:705:18)\n at tryOnImmediate (timers.js:676:5)\n at processImmediate (timers.js:658:5)","host":"translate.google.com","hostname":"translate.google.com","method":"GET","path":"/translate_a/single?client=t&sl=en&tl=vi&hl=vi&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=32434&tk=560583.924797","statusCode":503,"statusMessage":"Service Unavailable","code":"BAD_REQUEST"

**Comment by vitalets** [comment]
Looks like one-time network/server issue. Now it's working?

**Comment by nvtuan305** [comment]
> Looks like one-time network/server issue. Now it's working?

Thank for your quick response! I still get the same issue. Can you give more detail about this issue?

**Comment by vitalets** [comment]
When having this error could make a direct request from terminal to provided url (copied from error description). Like this:
```
curl -I "https://translate.google.com/translate_a/single?client=t&sl=en&tl=vi&hl=vi&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=32434&tk=560583.924797"
```

**Comment by JouzaLoL** [comment]
I think this happens when you make too many requests. Is there any way to circumvent this other than a VPN?

**Comment by vitalets** [comment]
As all tests [are passing every day](https://travis-ci.org/vitalets/google-translate-api/builds) this looks like not an issue of library itself.

**Comment by coltongit** [comment]
It might be OK to close this as a result of such a finding.

**Comment by vitalets** [comment]
> May I suggest introducing an error message into the library stating that this error happens due to too many requests?

Could you show an example of such error message?

**Comment by nvtuan305** [comment]
> I think this happens when you make too many requests.
I think so, my server maybe call too many requests at the same time.

**Comment by coltongit** [comment]
> > I think this happens when you make too many requests.
> 
> I think so, my server maybe call too many requests at the same time.

This could be referenced via an addition in the readme. If too many requests are made, you can either end up with a 429 or a 503 error.

**Comment by vitalets** [comment]
Now you can [setup proxy](https://github.com/vitalets/google-translate-api#too-many-requests) to bypass limits.
