### ISSUE TITLE
says I have to pay for more now??

### ISSUE THREAD

**Issue by JShep89** [vitalets/google-translate-api#30]
:japanese_ogre:  Unhandled promise rejection
Unhandled Rejection at:{}reason:HTTPError: Response code 429 (Too Many Requests)
Url: https://translate.google.com/translate_a/single?client=gtx&sl=en&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=test&tk=157051.326272

**Comment by ZyC0R3** [comment]
`Url: https://translate.google.com/translate_a/single?client=gtx&sl=en&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=and%20gone&tk=897943.725889`

`Url: https://translate.google.com/translate_a/single?client=gtx&sl=en&tl=de&hl=de&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=20%20hours&tk=775898.882380`

Seems to be more common, #3

**Comment by vitalets** [comment]
Now you can [setup proxy](https://github.com/vitalets/google-translate-api#too-many-requests) to bypass limits.
