### ISSUE TITLE
TKK generated

### ISSUE THREAD

**Issue by extensionsapp** [vitalets/google-translate-api#31]
Hey.

Did you manage to figure out how TKK is generated?

`var code = res.body.match(/TKK='.*?';/g);`

**TKK=** not found in HTML `https://translate.google.com`

![tkk](https://user-images.githubusercontent.com/8192379/61499949-aef40f00-a9d1-11e9-9bdb-948426f8d31a.png)

Where does TKK come from?

Maybe this: `tkk:'434303.3040823967'`

**Comment by vitalets** [comment]
Seems you are using outdated code.
Currently TKK is extracted via [vitalets/google-translate-token](https://github.com/vitalets/google-translate-token) in [this line](https://github.com/vitalets/google-translate-token/blob/0da30f7c74a37c772a954bc6d6a527a1ae15a90c/index.js#L85).

It uses regexp that matches your screenshot.
