### ISSUE TITLE
Creating /.config folder in root

### ISSUE THREAD

**Issue by Jubeng** [vitalets/google-translate-api#32]
This is occured when it is deployed in our server, the library is creating a .config folder
This is the error displayed
`Error: EACCES: permission denied, mkdir '/.config'`
Which is not allowed by our server.

**Comment by vitalets** [comment]
Library uses [configstore](https://github.com/yeoman/configstore) under the hood. According to docs you can define `$XDG_CONFIG_HOME` env var to overwrite default location.
Feel free to reopen if it will not help.
