### ISSUE TITLE
About the languages.js

### ISSUE THREAD

**Issue by xfslove** [vitalets/google-translate-api#33]
the 
```
{
    'zh': 'Chinese (Simplified)',
    'zh-cn': 'Chinese (Simplified)',
    'zh-tw': 'Chinese (Traditional)'
}
```
are not working when the key in view url(the translate api works with the lowercase key, but the view url not works).

eg: 
`https://translate.google.com/#view=home&op=translate&sl=en&tl=zh-cn&text=hello`
the view will not shown the translation, but tl=**zh-CN** works.

its case sensitive. seems only support **zh-CN**, **zh-TW**.

I think update those key to uppercase is better.

**Comment by vitalets** [comment]
Good catch. could you make a PR?

**Comment by xfslove** [comment]
sure. I'll make a PR.
