### ISSUE TITLE
Could I use this library on Ionic 4 on a Typescript file?

### ISSUE THREAD

**Issue by manel00** [vitalets/google-translate-api#35]
Hi,

First of all, thanks for such nice library, i'm looking for translate once click a button on ionic 4, but i don't know if it works like that, i'm a newbie on this.

**UPDATED**

I have errors:

> [ng] ERROR in ./node_modules/@vitalets/google-translate-token/node_modules/got/index.js
> [ng] Module not found: Error: Can't resolve './package' in '.................../node_modules/@vitalets/google-translate-token/node_modules/got'
> [ng] ERROR in ./node_modules/osenv/osenv.js
> [ng] Module not found: Error: Can't resolve 'child_process' in '....................../node_modules/osenv'
> [ng] ERROR in ./node_modules/got/source/utils/get-body-size.js
> [ng] Module not found: Error: Can't resolve 'fs' in '.................../node_modules/got/source/utils'
> [ng] ERROR in ./node_modules/graceful-fs/graceful-fs.js
> [ng] Module not found: Error: Can't resolve 'fs' in '........................../node_modules/graceful-fs'
> [ng] ERROR in ./node_modules/mkdirp/index.js
> [ng] Module not found: Error: Can't resolve 'fs' in '................................./node_modules/mkdirp'
> [ng] ERROR in ./node_modules/got/source/utils/timed-out.js
> [ng] Module not found: Error: Can't resolve 'net' in '......................./node_modules/got/source/utils'

Thank you so much

**Comment by coltongit** [comment]
I wonder if this is related to the permissions of the server used for the translation or something. It's not an API error itself.

**Comment by vitalets** [comment]
Hi! This library is for Node.js so it does not work in Ionic 4 (as it does not provide system modules such as `fs`, `net`, etc).
