### ISSUE TITLE
Unable to resolve module `querystring`

### ISSUE THREAD

**Issue by waqaramjad** [vitalets/google-translate-api#38]
i am getting that error 
` bundling failed: Error: Unable to resolve module `querystring` from `E:\React Native\react-native-multi-language-app\node_modules\@vitalets\google-translate-api\index.js`: Module `querystring` does not exist in the Haste module map`

**Comment by vitalets** [comment]
Created issue for supporting react-native: https://github.com/vitalets/google-translate-api/issues/42
