### ISSUE TITLE
translation quality

### ISSUE THREAD

**Issue by lavolp3** [vitalets/google-translate-api#39]
Is there any way to control the quality of the translation? 
I have the feeling that my translations are of very bad quality, especially since I reactivated my module a few days ago after several months.
translate.google.com gives much better results.

Sample:
"In 1980, a Las Vegas hospital suspended workers for betting on when patients would die!"

translate.google.com:
"1980 suspendierte ein Krankenhaus in Las Vegas Arbeiter, weil sie darauf gewettet hatten, wann Patienten sterben würden!" (very good)

My App:
` translate(result, { from: 'en', to: 'de' })
.then(function(result) {
    console.log(result.text);
}).catch(function(e) {
    console.log("[MMM-rfacts] Translation ERROR! Translation failed, will fall back to English.");
});`

Result:
"Im Jahr 1980 suspendierten ein Las Vegas Krankenhausmitarbeiter für Wetten auf, wenn Patienten sterben würden!" (bad quality)

**Comment by xfslove** [comment]
hi, @lavolp3 . you could set the `client=gtx`. and it will get the result you expected.

**Comment by lavolp3** [comment]
Works like a charm! Thanks! What does `client: gtx` mean? I can't find any reference/description for that.

**Comment by xfslove** [comment]
I'm not sure what the `client:gtx` means. maybe the `client:gtx` will use the newest translation api of google.

I just catch the `translate.google.com` request found the `client` is different, the `translate.google.com` parameter is `client=webapp`, and I tried the `gtx`, works too.

**Comment by lavolp3** [comment]
Closing this since its resolved. However I'd still be interested in the source of this client option
