### ISSUE TITLE
Punjabi is using the wrong language code, Simplified Chinese doesn't use both the 'zh' and 'zh-cn' language codes, and Hebrew doesn't use both the 'he' and 'iw' language codes in languages.js (China also cannot use this library either, so this will fix that as well)

### ISSUE THREAD

**Issue by coltongit** [vitalets/google-translate-api#4]
The language code for Punjabi is labelled as `ma` when it should be `pa`. `ma` will just give the source string when trying to translate into Punjabi, while `pa` will give the proper Punjabi translation. Hebrew translations are supported under both the `he` and `iw` language codes, but only `iw` is supported in this module (same goes for Simplified Chinese where both `zh` and `zh-cn` language codes are supported for translations, but only `zh-cn` is supported in this module). China also has the main Translate URL (`translate.google.com`) banned, so allowing for anyone to use any language Translate URL they wish will fix this issue. A PR has been created to allow these issues to be fixed (PRs #6, #7, and https://github.com/vitalets/google-translate-token/pull/2). These are all long-standing issues that have persisted since the days of the original repo (see https://github.com/matheuss/google-translate-api/issues/48, https://github.com/matheuss/google-translate-api/issues/59, https://github.com/matheuss/google-translate-api/issues/60, https://github.com/matheuss/google-translate-api/issues/62, https://github.com/matheuss/google-translate-api/issues/68, and https://github.com/matheuss/google-translate-token/issues/10 for more details on this). (https://github.com/matheuss/google-translate-api/issues/48, https://github.com/matheuss/google-translate-api/issues/59, https://github.com/matheuss/google-translate-api/issues/62, and https://github.com/matheuss/google-translate-api/issues/68 have been fixed already).

**Comment by vitalets** [comment]
As PRs are merged this can be closed.
