### ISSUE TITLE
how to disable auto capital 

### ISSUE THREAD

**Issue by AshoneA** [vitalets/google-translate-api#40]
I translated this sentence from Chinese to English like `{taskCode} | {qcConfigName}的质检报告通过失败`. I got a translate sentence that is `{taskCode} | {qcConfigName}'s quality report failed` from google translate in website(https://translate.google.com/). But i got a sentence that is `{TaskCode} | {qcConfigName} inspection report by failure` in @vitalets/google-translate-api.
Can i get a result without first letter is capital like google translate website that .

**Comment by xfslove** [comment]
hi, @AshoneA , I test your input, and got the result you expected. you could have a try with `client=gtx`

**Comment by AshoneA** [comment]
@xfslove Thanks a lot, it's work!
