### ISSUE TITLE
Return the converted text

### ISSUE THREAD

**Issue by jbrhinalyn** [vitalets/google-translate-api#46]
Hi,

This api is really helpful.
I have a question.

The translation is success based on the console.log(). Is there a way to return the converted text?

Thanks. Help is highly appreciated.

**Comment by vitalets** [comment]
Hi! Could you show code example and what actually you expect to be returned.

**Comment by jbrhinalyn** [comment]
I used your existing code.

translate('Ik spreek Engels', {to: 'en'}).then(res => {
    return res.text;
    //=> I speak English
    console.log(res.from.language.iso);
    //=> nl
}).catch(err => {
    console.error(err);
});

**Comment by vitalets** [comment]
Looks ok! What's the question?
