### ISSUE TITLE
XO Updated

### ISSUE THREAD

**Issue by ZyC0R3** [vitalets/google-translate-api#47]
XO has been updated from the version this API is currently using 0.16.0 to 0.28.1

in V0.18.0 it added in 21 new rules: (https://github.com/xojs/xo/releases/tag/v0.18.0)
Unicorn plugin: sindresorhus/eslint-plugin-unicorn@v1.0.0...v2.1.0
no-array-instanceof
no-new-buffer
no-hex-escape
number-literal-case
escape-case
prefer-starts-ends-with
custom-error-definition
type-error
AVA plugin: avajs/eslint-plugin-ava@a0156f1
no-async-fn-without-await
no-duplicate-modifiers

When you update this dependency to 0.28.0 or even past 0.17.0 it breaks the testing in travis, but the api still works in the deployment i use, is there anyway you will be able to update the XO Dependancy and the test to use the latest version.

**Comment by vitalets** [comment]
could you make a PR with latest XO version and make tests passing?

**Comment by ZyC0R3** [comment]
I can not seem to fix this issue or get the tests to pass. Are you able to fix this.

**Comment by vitalets** [comment]
In new [release v9](https://github.com/vitalets/google-translate-api/issues/70#issuecomment-1282886088) XO was replaced with eslint.
