### ISSUE TITLE
While executing translate("Hello Welcome to my world",{to:"ar"}).then((transText) =>{            console.log(transText)        })

### ISSUE THREAD

**Issue by rajeshmts07** [vitalets/google-translate-api#52]
./node_modules/@vitalets/google-translate-token/node_modules/got/index.js
Module not found: Error: Can't resolve './package' in 'C:\Users\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got'
resolve './package' in 'C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got'
  using description file: C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package.json (relative path: .)
    using description file: C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package.json (relative path: ./package)
      no extension
        C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package doesn't exist
      .ts
        C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package.ts doesn't exist
      .js
        C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package.js doesn't exist
      as directory
        C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package doesn't exist
[C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package]
[C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package.ts]
[C:\CypressProject\node_modules\@vitalets\google-translate-token\node_modules\got\package.js]
 @ ./node_modules/@vitalets/google-translate-token/node_modules/got/index.js 19:12-32
 @ ./node_modules/@vitalets/google-translate-token/index.js
 @ ./node_modules/@vitalets/google-translate-api/index.js
 @ ./cypress/integration/pages/SearchPage.ts
 @ ./cypress/integration/stepdefinitions/HomePageStepDef.ts
 @ ./cypress/integration/features/SearchE2E.feature
 @ multi ./cypress/integration/features/SearchE2E.feature

./node_modules/got/source/utils/timed-out.js
Module not found: Error: Can't resolve 'net' in 'C:\CypressProject\node_modules\got\source\utils'
resolve 'net' in 'C:\CypressProject\node_modules\got\source\utils'
  Parsed request is a module
  using description file: C:\CypressProject\node_modules\got\package.json (relative path: ./source/utils)
    resolve as module
      \CypressProject\node_modules\got\source\utils\node_modules doesn't exist or is not a directory
      \CypressProject\node_modules\got\source\node_modules doesn't exist or is not a directory
      \CypressProject\node_modules\node_modules doesn't exist or is not a directory
      \node_modules doesn't exist or is not a directory
      \node_modules doesn't exist or is not a directory
      \node_modules doesn't exist or is not a directory
      \node_modules doesn't exist or is not a directory
      \node_modules doesn't exist or is not a directory
      looking for modules in C:\CypressProject\node_modules
        using description file: C:\CypressProject\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in \node_modules
        using description file: \package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\CypressProject\package.json (relative path: ./node_modules/net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: \package.json (relative path: ./node_modules/net)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\CypressProject\node_modules\got\node_modules
        using description file: C:\CypressProject\node_modules\got\package.json (relative path: ./node_modules)
          using description file: C:\CypressProject\node_modules\got\package.json (relative path: ./node_modules/net)
            no extension
              C:\CypressProject\node_modules\got\node_modules\net doesn't exist
              C:\CypressProject\node_modules\net doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              \node_modules\net doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
            .ts
              C:\CypressProject\node_modules\got\node_modules\net.ts doesn't exist
              C:\CypressProject\node_modules\net.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              \node_modules\net.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
            .js
              C:\CypressProject\node_modules\got\node_modules\net.js doesn't exist
              C:\CypressProject\node_modules\net.js doesn't exist
              \node_modules\net.js doesn't exist
            as directory
              C:\CypressProject\node_modules\got\node_modules\net doesn't exist
            as directory
              C:\CypressProject\node_modules\net doesn't exist
            as directory
              \node_modules\net doesn't exist
[C:\CypressProject\node_modules\got\source\utils\node_modules]
[C:\CypressProject\node_modules\got\source\node_modules]
[C:\CypressProject\node_modules\node_modules]
[C:\node_modules]
[C:\node_modules]
[C:\\node_modules]
[C:\Users\node_modules]
[C:\node_modules]
[C:\CypressProject\node_modules\got\node_modules\net]
[C:\CypressProject\node_modules\net]
[\node_modules\net]
[C:\CypressProject\node_modules\got\node_modules\net.ts]
[C:\CypressProject\node_modules\net.ts]
[\node_modules\net.ts]
[C:\CypressProject\node_modules\got\node_modules\net.js]
[C:\CypressProject\node_modules\net.js]
[\node_modules\net.js]
 @ ./node_modules/got/source/utils/timed-out.js 2:12-26
 @ ./node_modules/got/source/request-as-event-emitter.js
 @ ./node_modules/got/source/as-promise.js
 @ ./node_modules/got/source/create.js
 @ ./node_modules/got/source/index.js
 @ ./node_modules/@vitalets/google-translate-api/index.js
 @ ./cypress/integration/pages/SearchPage.ts
 @ ./cypress/integration/stepdefinitions/HomePageStepDef.ts
 @ ./cypress/integration/features/SearchE2E.feature
 @ multi ./cypress/integration/features/SearchE2E.feature

./node_modules/defer-to-connect/dist/index.js
Module not found: Error: Can't resolve 'tls' in 'C:\CypressProject\node_modules\defer-to-connect\dist'
resolve 'tls' in 'C:\CypressProject\node_modules\defer-to-connect\dist'
  Parsed request is a module
  using description file: C:\CypressProject\node_modules\defer-to-connect\package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      C:\CypressProject\node_modules\defer-to-connect\dist\node_modules doesn't exist or is not a directory
      C:\CypressProject\node_modules\defer-to-connect\node_modules doesn't exist or is not a directory
      C:\CypressProject\node_modules\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      C:\\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\CypressProject\node_modules
        using description file: C:\CypressProject\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in \node_modules
        using description file: \package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\CypressProject\package.json (relative path: ./node_modules/tls)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: \package.json (relative path: ./node_modules/tls)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\CypressProject\node_modules\tls doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              \node_modules\tls doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\CypressProject\node_modules\tls.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              \node_modules\tls.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\CypressProject\node_modules\tls.js doesn't exist
              \node_modules\tls.js doesn't exist
            as directory
              C:\CypressProject\node_modules\tls doesn't exist
            as directory
              \node_modules\tls doesn't exist
[C:\CypressProject\node_modules\defer-to-connect\dist\node_modules]
[C:\CypressProject\node_modules\defer-to-connect\node_modules]
[C:\CypressProject\node_modules\node_modules]
[C:\node_modules]
[C:\node_modules]
[C:\\node_modules]
[C:\Users\node_modules]
[C:\node_modules]
[C:\CypressProject\node_modules\tls]
[\node_modules\tls]
[C:\CypressProject\node_modules\tls.ts]
[\node_modules\tls.ts]
[C:\CypressProject\node_modules\tls.js]
[\node_modules\tls.js]
 @ ./node_modules/defer-to-connect/dist/index.js 3:14-28
 @ ./node_modules/@szmarczak/http-timer/source/index.js
 @ ./node_modules/got/source/request-as-event-emitter.js
 @ ./node_modules/got/source/as-promise.js
 @ ./node_modules/got/source/create.js
 @ ./node_modules/got/source/index.js
 @ ./node_modules/@vitalets/google-translate-api/index.js
 @ ./cypress/integration/pages/SearchPage.ts
 @ ./cypress/integration/stepdefinitions/HomePageStepDef.ts
 @ ./cypress/integration/features/SearchE2E.feature
 @ multi ./cypress/integration/features/Search.feature

**Comment by Odame** [comment]
@rajeshmts07 Were you able to resolve this?

**Comment by vitalets** [comment]
Please try new v5.0.0, it does not use `google-translate-token` any more.
