### ISSUE TITLE
translations from english to dutch are not as good as online google translations.

### ISSUE THREAD

**Issue by janvda** [vitalets/google-translate-api#53]
I am using node-red node https://github.com/idocme/translate-red-node
which is a thin wrapper around this library for the translation of English text to Dutch text.

I would expect it to have same quality as the online google translate site (https://translate.google.com/?um=1&ie=UTF-8&hl=nl&client=tw-ob#en/nl/) but this is not the case.

**Comment by xfslove** [comment]
you can try with set the `client=gtx`.

**Comment by vitalets** [comment]
Please try the new v5.0.0 that uses new google api.
Maybe quality will be ok now.
