### ISSUE TITLE
Issue in using Chinese Traditional and Chinese Simplified

### ISSUE THREAD

**Issue by SinghDivyajeet** [vitalets/google-translate-api#55]
turn zh-CN and zh-TW in languages.js into lowerCase because getCode function in language.js converts the parameter into lowerCase but while matching it in langs object, It can't find because zh-CN and zh-TW are in upper case.

**Comment by xfslove** [comment]
See #33 .
 
You could using the zh-CN & zh-TW as key. like [the test](https://github.com/vitalets/google-translate-api/blob/ec520a050903d247f67faf93fab64cb78d3ba4dd/test.js#L195).
