### ISSUE TITLE
Error 413: Request Entity too large

### ISSUE THREAD

**Issue by Gaureesh-Shenoy** [vitalets/google-translate-api#57]
Hi,

First of all, a great thanks for creating this npm package and it works for most cases.

There is but one issue I observed while using it - 413: Request Entity too large. This happened in some cases

I am unable to understand why this error occurs and how to avoid it. 

Also is there any limitation on usage - such as number of requests or frequency of requests that I should know?

Would appreciate if you could help with this

Regards,
Gaureesh

**Comment by Prottoy2938** [comment]
Did you found the solution?

**Comment by hassanrazzaqshaikh** [comment]
Is there a solution to convert long text? it seems that you are using query string and it has limit. Cant it be through post

**Comment by mpuz** [comment]
> Is there a solution to convert long text? it seems that you are using query string and it has limit. Cant it be through post


You can process by chunks
```
const chunk = (arr, size) => arr.reduce((acc, e, i) => (i % size ? acc[acc.length - 1].push(e) : acc.push([e]), acc), []);

const sentenceArray = articleInput.split('. ') // split article to array by sentence
var grouped = chunk(sentenceArray, CHUNK_SIZE) // make array of chunks 
for (chunk of grouped) { // process by chunks
console.log(chunk.join('. '))
}
```

**Comment by vitalets** [comment]
Please try splitting on chunks as @mpuz suggested.
