### ISSUE TITLE
Error! Unable to issue local certificate

### ISSUE THREAD

**Issue by Gaureesh-Shenoy** [vitalets/google-translate-api#58]
Hi,

While using it in a server, I get the error 'Unable to issue local certificate'.

I know it is not an issue with this package. But could you help with this in case you have come across such errors before?

**Comment by vitalets** [comment]
I hope this [SO thread](https://stackoverflow.com/questions/23885449/unable-to-resolve-unable-to-get-local-issuer-certificate-using-git-on-windows) may be helpful.
