### ISSUE TITLE
Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by 7thghoul** [vitalets/google-translate-api#60]
Response code 403 (Forbidden)
Url: https://translate.google.com/translate_a/single?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=%20hello%20&tk=723989.723989

**Comment by LadySara48** [comment]
I'm getting the same error and I can't use it

**Comment by Trunks8257** [comment]
same

**Comment by 6R36** [comment]
Same problem.
Is the project still maintained?

**Comment by yxmg** [comment]
same problem，use translate.google.cn

**Comment by poowu** [comment]
Same problem.
Is the problem with the "client=t " ?

**Comment by Natemo6348** [comment]
same issue

**Comment by vkedwardli** [comment]
Seems the original API is dead after Google revamped the site, for those who can't wait for #61 
You can use my branch temporarily `vkedwardli/google-translate-api#batchexecute`

**Comment by ZyC0R3** [comment]
> Seems the original API is dead after Google revamped the site, for those who can't wait for #61
> You can use my branch temporarily `vkedwardli/google-translate-api#batchexecute`

The build test o. This version are mostly failing.

**Comment by vkedwardli** [comment]
> The build test on this version are mostly failing.

@ZyC0R3 I just run a test on my machine: `34 tests passed`
Can share your error log?

**Comment by ZyC0R3** [comment]
> > The build test on this version are mostly failing.
> 
> @ZyC0R3 I just run a test on my machine: `34 tests passed`
> Can share your error log?

https://travis-ci.com/github/ZyC0R3/google-translate-api

**Comment by vkedwardli** [comment]
@ZyC0R3 oops, thanks for pointing it out.
Since I'm not a JS dev, so I didn't release to npm and test on all versions.
But I will try to support v10 and above.

**Comment by vkedwardli** [comment]
Just tested on v15.5.0, all tests are passing 🤨

**Comment by vkedwardli** [comment]
@ZyC0R3 your CI build failed due to some gyp build issue, I've update the `coveralls` to `^2.11.11`, this should solve your issue

**Comment by ArtanisTheOne** [comment]
I think Zyc0r3 is referring to the old Google Translate API, from vitalets/google-translate-api

**Comment by xhemj** [comment]
same problem

**Comment by SurgicalCrow** [comment]
same problem!

**Comment by ArtanisTheOne** [comment]
@xhemj @SurgicalCrow Try this branch instead of `vitalets/google-translate-api`, it was revamped by @vkedwardli to fit Google's updated translation system

https://github.com/vkedwardli/google-translate-api#batchexecute

**Comment by vitalets** [comment]
Just released v5 that fixes the problem.
Please check and let me know if something goes wrong.

Thanks to all for reports and help!

**Comment by 7thghoul** [comment]
> Just released v5 that fixes the problem.
> Please check and let me know if something goes wrong.
> 
> Thanks to all for reports and help!

where have you been for so long?

**Comment by vkedwardli** [comment]
@7thghoul If you don't want to wait for the merge, you should have used my use my fork

**Comment by wahengchang** [comment]
how you guys fixed ? it work on my localhost, however it `Response code 403 (Forbidden)` on the server with a proper domain name

**Comment by 6R36** [comment]
I use another package: translatte.

https://github.com/extensionsapp/translatte#readme <https://github.com/extensionsapp/translatte#readme>
