### ISSUE TITLE
Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by SurgicalCrow** [vitalets/google-translate-api#63]
Response code 403 (Forbidden)
Url: https://translate.google.com/translate_a/single?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hella&tk=421803.421803

const { text: result, from } = await translate(text, { to: target, from: base });

**Comment by 34r7h** [comment]
same

**Comment by JerroldLee** [comment]
same

**Comment by 34r7h** [comment]
Here's a package that can be included in package.Json until the fix is merged. https://www.npmjs.com/package/@34r7h/google-translate-api

**Comment by vitalets** [comment]
Duplicates #60
