### ISSUE TITLE
BAD_REQUEST?

### ISSUE THREAD

**Issue by miliu99** [vitalets/google-translate-api#64]
I'm getting this error on my second try (first one worked - I believe):

Error
    at C:\mealyet\support\node_modules\google-translate-api\index.js:105:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
      code: 'BAD_REQUEST'
    }

I see all tests failed. Does it mean this component is no more working?

**Comment by vitalets** [comment]
1. Are you using the latest version v5?
2. If yes and error still occurs could you show the code the produces error?

thx

**Comment by golovewkin** [comment]
host: 'translate.google.com',
  hostname: 'translate.google.com',
  method: 'GET',
  path: '/translate_a/single?client=t&sl=auto&tl=ru&hl=ru&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=like&tk=997896.997896',
socketPath: undefined,
  protocol: 'https:',
  url: 'https://translate.google.com/translate_a/single?client=t&sl=auto&tl=ru&hl=ru&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=like&tk=997896.997896',

**Comment by golovewkin** [comment]
Yes, It's b/c of version. suddenly v4 stopped working, after installing v5, everithing is ok
