### ISSUE TITLE
.forEach error of null

### ISSUE THREAD

**Issue by ArtanisTheOne** [vitalets/google-translate-api#67]
Please look [at this issue](https://github.com/ZyC0R3/RitaBot/issues/264) for reference. 

Essentially specific words trigger the .forEach error, not links as you said before 

If you use the word "Good" and translate that to spanish from english the error shall be thrown and no translation shall be provided. These words or phrases which result in the dropping of the translation due to an empty value in the arrays is causing these issues and I have no possible idea as to why this would occur.

Any ideas on why and how to fix it? @vitalets @vkedwardli

**Comment by vkedwardli** [comment]
I'm not getting any error

```javascript
translate('Good', {from: 'english', to: 'spanish'})
```

returns

```
{
  text: 'Bien',
  pronunciation: null,
  from: {
    language: { didYouMean: false, iso: 'en' },
    text: { autoCorrected: false, value: '', didYouMean: false }
  },
  raw: [
    [ null, null, null, [Array] ],
    [ [Array], 'es', 1, 'en', [Array] ]
  ]
}
```

**Comment by vkedwardli** [comment]
Ok turns out it is a bit random, when Google decided to use gender specific translation the error could be triggered

**Comment by ArtanisTheOne** [comment]
Yeah, this happens a lot now. That's weird... Is there a possible fix or someway to tell Google not to use gender-specific translations?

**Comment by vkedwardli** [comment]
I don't know, but you can perform actions which is allowed in the Web UI

<img width="349" alt="Screenshot 2021-02-23 at 2 05 26 AM" src="https://user-images.githubusercontent.com/602245/108750221-bb602680-757b-11eb-9f72-823c68da3d05.png">
#68 now uses the first gender-specific result from Google
