### ISSUE TITLE
Can you please make a similar api for bing.com?

### ISSUE THREAD

**Issue by zyadomer98** [vitalets/google-translate-api#69]
Could you please make another great api for us like this one but instead of using google translate, use Microsoft translate?

https://www.bing.com/translator

**Comment by plainheart** [comment]
Hi, I made a simple [bing API](https://github.com/plainheart/bing-translate-api), feel free to try it.

**Comment by vitalets** [comment]
@plainheart awesome!

**Comment by zyadomer98** [comment]
@plainheart Thank you very much, it is really awesome. Can you please let me know if it is possible to convert speech to text through http requests to this website https://azure.microsoft.com/en-us/services/cognitive-services/speech-to-text/#features? I tried a lot and could not make it because it uses websocket.

**Comment by plainheart** [comment]
Hi, @zyadomer98, It is indeed so complicated. Sorry I can't do more for you.
