### ISSUE TITLE
Punctuation Problem.

### ISSUE THREAD

**Issue by sudis** [vitalets/google-translate-api#73]
Hi! When I put any punctuation, it connects all the text. I have given examples below. 

![Screen Shot 2021-04-12 at 10 57 39](https://user-images.githubusercontent.com/72707666/114368772-065ee900-9b7e-11eb-8131-49bf6838bad7.png)

![Screen Shot 2021-04-12 at 10 57 57](https://user-images.githubusercontent.com/72707666/114368748-ffd07180-9b7d-11eb-8959-ad0d83d8f7b7.png)

Is it a bug? 

Sincerely.

**Comment by vitalets** [comment]
I've checked - seems Google api splits text per sentences and returns translations of separate sentence.
When on the library side we join results back - [spaces are not inserted](https://github.com/vitalets/google-translate-api/blob/ba87de2178f31a787f996c9bcc59e53623bdc303/index.js#L96).

I've made a fix and will release as major update.

**Comment by sudis** [comment]
Does it take long for the new update to be published? I need quite a lot.

Sincerely.

**Comment by vitalets** [comment]
Released as 7.0.0
