### ISSUE TITLE
302 Error "Moved", Google api blocks my ip

### ISSUE THREAD

**Issue by levranger** [vitalets/google-translate-api#76]
I've been testing translations of a relatively large array and everything worked just fine but then is started throwing this error 
`{ HTTPError: Response code 302 (Found)
Url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-119779982342254410&bl=boq_translate-webserver_20210421.14_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=3394&rt=c
    at EventEmitter.emitter.on (/home/user/ploenta.com/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: 'translate.google.com',
  hostname: 'translate.google.com',
  method: 'POST',
  path:
   '/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-119779982342254410&bl=boq_translate-webserver_20210421.14_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=3394&rt=c',
  socketPath: undefined,
  protocol: 'https:',
  url:
   'https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-119779982342254410&bl=boq_translate-webserver_20210421.14_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=3394&rt=c',
  gotOptions:
   { path:
      '/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-119779982342254410&bl=boq_translate-webserver_20210421.14_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=3394&rt=c',
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'translate.google.com',
     port: null,
     hostname: 'translate.google.com',
     hash: null,
`
But when i switch my ip adress (VPN or Proxy), everything works just fine. In production mode i would not be able to swtich my ip everytime i got blocked. Are there any thoughts?

**Comment by vitalets** [comment]
Using such api for free always has risks. Maybe using paid official api is better for your case..
