### ISSUE TITLE
how can use this library continuously?,  i'm facing with this error and it doesn't work correctly

### ISSUE THREAD

**Issue by hasanakbari118** [vitalets/google-translate-api#77]
Dear support team
many thanks for your good library, but meanwhile many times facing with this error :

unhandledRejection TypeError: Cannot read property '1' of null
4|srt.negarkhane.com  | Url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute?rpcids=MkEWBc&f.sid=-6889561876437169181&bl=boq_translate-webserver_20210502.17_p0&hl=en-US&soc-app=1&soc-platform=1&soc-device=1&_reqid=5158&rt=c

my code : 
`const translate = require('@vitalets/google-translate-api');`
`router.post('/translateTxt', (req, res, next) => {
    const txt = req.body.txt;
    translate(txt, { to: 'fa' }).then(tr => {
        res.status(200).json({ translate: tr.text })
    })
})`

**Comment by vitalets** [comment]
> my code :
> `const translate = require('@vitalets/google-translate-api');`
> `router.post('/translateTxt', (req, res, next) => { const txt = req.body.txt; translate(txt, { to: 'fa' }).then(tr => { res.status(200).json({ translate: tr.text }) }) })`

What was the txt you tried to translate?

**Comment by yennyles** [comment]
Hi, i got the same error, when translate this: 
Mengadili Menyatakan TerdakwaDIDI SAPUTRA Pgl DIDItersebut diatas terbukti secara sah dan meyakinkan bersalah melakukan tindak pidana Menyalahgunakan Narkotika Golongan I Bagi Diri Sendiri sebagaimana dalam dakwaan keempat Menjatuhkan pidana kepada Terdakwaoleh karena itu dengan pidana penjara selama1 (satu) Tahun dan 6 (enam) bulan Menetapkan masa penangkapan dan penahanan yang telah dijalani Terdakwadikurangkan seluruhnya dari pidana yang dijatuhkan Menetapkan Terdakwa tetap ditahan Menetapkan barang bukti berupa 1 (satu) paket kecil narkotika jenis shabu shabu yang dibungkus dengan plastik bening yang disimpan di dalam rokok Marlboro merah 1 (satu) buah tas sandang kecil warna hitam merk Cardiny 1 (satu) buah bong tersambung dengan kaca pirek dan sedotan bercabang yang terbuat dari botol plastik bening dengan tutup botol coklat 2 (dua) buah mencis warna hijau dan ungu Dirampas untuk dimusnahkan Uang tunai sebanyak Rp 100 000 (seratus ribu rupiah) dalam bentuk 2 (dua) lembar uang pecahan Rp 50 000 (lima puluh ribu rupiah) Dirampas untuk Negara 1 (satu) unit sepeda motor Kawasaki ninja warna biru hitam BM 6539 OA Dikembalikan kepada Terdakwa Didi Saputra Pgl DidiMembebankan kepada Terdakwa membayar biaya perkarasejumlah Rp 3 000 (tiga ribu rupiah)

first I got the translation, but then I got the error. how i could  solve this error? is my IP address was blocking by Google bcause too many request?

**Comment by vitalets** [comment]
I've rechecked - it works on my side.
Maybe IP is blocking, yes.
