### ISSUE TITLE
Translation Accuracy

### ISSUE THREAD

**Issue by ArtanisTheOne** [vitalets/google-translate-api#79]
Due to Google adding a new header, `X-Goog-BatchExecute-Bgr` requests that are made without this header get different and seemingly worse translations from the API. 

It seems to be somewhat based on the query string of the translation, so to be able to generate it we need to extract the algorithm which generates it on the google translate website. 

A big and difficult issue to solve

**Comment by vitalets** [comment]
Yes( Main discussion for that is in https://github.com/vitalets/google-translate-api/issues/70
