### ISSUE TITLE
Translating to Traditional Chinese translates to Simplified Chinese instead

### ISSUE THREAD

**Issue by coltongit** [vitalets/google-translate-api#8]
A minor bug I noticed after PR #6. It's that the value of `text.from.language.iso` is undefined when you auto-translate from Simplified or Traditional Chinese (the way `text.from.language.iso` is generated might have to be tweaked to fix this bug).
Example: Translating 你好 should result in `text.from.language.iso` being one of the language codes for Chinese Simplified, but it returns undefined instead when translated.

**Comment by vitalets** [comment]
Could you show an example code demonstrating that bug?
So that I will be able to convert it to test case and think about the fix.
Thanks!

**Comment by coltongit** [comment]
It turns out that the bug isn't actually that it showed as undefined (as it doesn't), but rather that it always translates to Simplified Chinese regardless of what value you put in (`zh-cn` and `zh-tw` end up translating to Simplified Chinese, even though they show what they're supposed to).

Code that demonstrates this bug:
```js
var translatedtext
translate('hello', {
from: 'en', to: 'zh-tw'
}).then(text=>{
console.log(text.from.language.iso) // should show as zh-tw, but shows as zh-cn instead
translatedtext=text.text
})```

**Comment by vitalets** [comment]
Is google translate web version behave the same way with `zh-cn`, and `zh-tw`?

**Comment by coltongit** [comment]
> Is google translate web version behave the same way with `zh-cn`, and `zh-tw`?

No. The web version only has one Chinese option, however, the API itself has `zh-tw` as a supported language code (see https://cloud.google.com/translate/docs/languages)
