### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by newbiE247** [vitalets/google-translate-api#9]
Using DiscordJs i'm mapping through all channels to translate a message to different languages at the same time. This obv. leads to HTTP 429. It worked for a week, but now it stoped working. Looking at the code i can see it throws and i start to wonder why it was working all the time in the first place. Do you have any advice for me, how to deal with this?

Also can you add an option to make it not translate certain pattern? For me it would be everything between < >. Thanks.

**Comment by vitalets** [comment]
Could you provide a demo code and error stacktraces? It would be helpful!

**Comment by vitalets** [comment]
As all tests [are passing every day](https://travis-ci.org/vitalets/google-translate-api/builds) this looks like not an issue of library itself.
Feel free to open if needed.

**Comment by trollderius** [comment]
```
(node:6499) UnhandledPromiseRejectionWarning: HTTPError: Response code 429 (Too Many Requests)
Url: https://translate.google.com/translate_a/single?client=t&sl=en&tl=es&hl=es&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=Hii&tk=949484.584575
    at stream.catch.then.data (/var/www/html/comoquiero/node_modules/@vitalets/google-translate-api/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Multi-Thinker** [comment]
+1 i have this exact same issue. 
assume i have a blog in different language, i provide title of post in English and translate it to two languages. 

daily i have about 40 translation requests.. 
the response is as follows: 
`{ HTTPError: Response code 429 (Too Many Requests)
Url: https://translate.google.com/translate_a/single?client=t&sl=en&tl=ur&hl=ur&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=Muhammad&tk=31862.451967
    at stream.catch.then.data (/var/www/app.fruityfifty.com/node_modules/got/index.js:123:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  message: 'Response code 429 (Too Many Requests)\nUrl: https://translate.google.com/translate_a/single?client=t&sl=en&tl=ur&hl=ur&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=Muhammad&tk=31862.451967',
  host: 'translate.google.com',
  hostname: 'translate.google.com',
  method: 'GET',
  path: '/translate_a/single?client=t&sl=en&tl=ur&hl=ur&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=Muhammad&tk=31862.451967',
  statusCode: 429,
  statusMessage: 'Too Many Requests',
  code: 'BAD_REQUEST' }
`

**Comment by vitalets** [comment]
@Multi-Thinker 
When translating on two languages do you send requests simultaneously? 
It looks like not daily limit (40 requests should be ok), but too frequent requests limit.

**Comment by genikineg** [comment]
> @Multi-Thinker
> When translating on two languages do you send requests simultaneously?
> It looks like not daily limit (40 requests should be ok), but too frequent requests limit.


What is the daily limit?

**Comment by Multi-Thinker** [comment]
> What is the daily limit?
40 requests, one request per 5 second. I've solved this by adding delay and changing client from t to ctx or ctx to t whenever one client response in error.
