### ISSUE TITLE
Support for newly added language.

### ISSUE THREAD

**Issue by yonas-g** [vitalets/google-translate-api#97]
^ as the title.

**Comment by Dhamu143** [comment]
Hi, @yonas-g  @AidanWelch @vitalets  not sure why this pull request is still open. I need those newly added languages. do you know how can I consume this?

**Comment by AidanWelch** [comment]
> Hi, @yonas-g @AidanWelch @vitalets not sure why this pull request is still open. I need those newly added languages. do you know how can I consume this?

@Dhamu143 I have implemented a feature in my forh here: https://github.com/AidanWelch/google-translate-api

forceFrom and forceTo should help you, if the languages are not already added, but I plan to update to all the supported languages soon.

**Comment by vitalets** [comment]
New languages added
