### ISSUE TITLE
Translate array of strings

### ISSUE THREAD

**Issue by Volodymyr-sky** [vitalets/google-translate-api#98]
Is there a way to translate array of separate strings in one request?
I tried JSON.stringify, but in some cases I recieve text with deleted quotes, so I can't JSON.parse() to get array

**Comment by AidanWelch** [comment]
Not within this API, and as far as I'm aware it is not possible in one request with the exposed endpoints of translate.google.com

**Comment by AidanWelch** [comment]
Its not possible reliably that I know in 1 request, but I have it down to 1 + n requests, instead of 2n requests in my fork [here](https://github.com/AidanWelch/google-translate-api)

**Comment by vitalets** [comment]
Duplicate of #101
